name             'commvault'
maintainer       'Taliesin Sisson'
maintainer_email 'taliesins@yahoo.com'
license          'All rights reserved'
description      'Installs/Configures commvault'
long_description 'Installs/Configures commvault'
version          '0.1.0'
depends          'seven_zip'
depends          'windows', '>= 1.2.6'
depends          'windows_firewall'